# Generated by Django 5.2 on 2025-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField()),
                ('time_of_day', models.IntegerField()),
                ('signal_strength', models.FloatField()),
                ('traffic_type', models.IntegerField()),
                ('rbs', models.IntegerField(default=0)),
            ],
        ),
    ]
