# Generated by Django 5.2 on 2025-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('indoor_temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('server_load', models.FloatField()),
                ('external_temp', models.FloatField()),
                ('ac_level', models.FloatField()),
                ('fans_active', models.FloatField()),
                ('hour', models.FloatField()),
            ],
        ),
    ]
