# Generated by Django 5.2 on 2025-04-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_maintenance', models.DateField()),
                ('next_maintenance', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('maintenance', 'maintenance'), ('expired', 'expired')], default='active', max_length=20)),
                ('time_left', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
