# Generated by Django 5.2 on 2025-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='id_rfid',
            field=models.CharField(max_length=100),
        ),
    ]
